### PR TITLE
Update load-functions.php

### PR DESCRIPTION
**Pull request by tut4ever**
fix warning error

### CODE REVIEW

**Comment by kadimi** [comment]
+1, I got a notice and a warning just after enabling the theme, Runway Framework on a site part of a WordPress network:

> ( ! ) Warning: Illegal string offset 'Icon' in /[...]/themes/Runway-Framework/runway-framework/framework/includes/load-functions.php on line 608

And:

> ( ! ) Notice: Uninitialized string offset: 0 in /[...]/themes/Runway-Framework/runway-framework/framework/includes/load-functions.php on line 608

**Comment by parallelus** [comment]
This was fixed in the core a while ago. If you are getting that error you need to download a newer version of Runway. Either the Master or Develop branch will have that patched. 

Master branch: https://github.com/parallelus/Runway-Framework/archive/master.zip
Develop branch: https://github.com/parallelus/Runway-Framework/archive/develop.zip

**Comment by parallelus** [comment]
The version with your changes appears to already have the fix for this issue. We made the changes in the following commit back in May 2015: 
https://github.com/parallelus/Runway-Framework/commit/02349451dbbb35d53986348672e4f6538fd5fba6

It's possible this is another issue, however I'm currently using the theme on several network installs and not seeing the error message. If you can confirm that the latest version from the Develop branch doesn't fix this for you we can reopen the issue.

**Comment by parallelus** [comment]
I went ahead and applied similar code to the Develop branch and pushed it. The warning message posted by @kadimi would mean that this won't be fixed by our previous update and the added error checking can't do any harm.

**Comment by kadimi** [comment]
@parallelus

- I later switched to a normal install and had the same errors
- I tried `develop`, same errors

Thank you for applying the change.

**Pull request closed without merging**
